name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1
    - run: cd docs/; sed 's/^\[/const data = \[/' ../data.json > data.json;
            julia -e 'using Pkg; Pkg.add(["NodeJS", "Franklin"]);
            using NodeJS; run(`$(npm_cmd()) install`);
            run(`$(npm_cmd()) run css-build`);
            using Franklin;
            Pkg.activate(".");Pkg.instantiate();
            optimize()'
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: docs/__site
